title: Brendan Anderson
email: bander2.imda@gmail.com
description: A web development blog.
baseurl: ""
url: "https://www.andersonproject.com"
enforce_ssl: "www.andersonproject.com"
twitter_username: andersonpro79
github_username: hcpss-banderson
author: Brendan Anderson

# Build settings
markdown: kramdown
highlighter: rouge

permalink: /posts/:title.html

kramdown:
  input: GFM
  syntax_highlighter: rouge

repository: bander2/bander2.github.io

gems:
  - jekyll-github-metadata
