title: Brendan Anderson
email: bander2.imda@gmail.com

description: >
  I'm a Web Developer who loves PHP, but also gets extra pumped about Ansible,
  Docker, and Composer.

baseurl:          ""
url:              "https://www.andersonproject.com"
enforce_ssl:      "www.andersonproject.com"
twitter_username: andersonpro79
github_username:  hcpss-banderson

# Build settings
markdown:    kramdown
highlighter: rouge

permalink: /posts/:title.html

kramdown:
  input: GFM
  syntax_highlighter: rouge

repository: bander2/bander2.github.io

gems:
  - jekyll-github-metadata
